---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookmgmt-rent
  labels:
    app: ebookmgmt-rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookmgmt-rent
  template:
    metadata:
      labels:
        app: ebookmgmt-rent
    spec:
      containers:
        - name: ebookmgmt-rent
          image: username/ebookmgmt-rent:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookmgmt-payment
  labels:
    app: ebookmgmt-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookmgmt-payment
  template:
    metadata:
      labels:
        app: ebookmgmt-payment
    spec:
      containers:
        - name: ebookmgmt-payment
          image: username/ebookmgmt-payment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookmgmt-book
  labels:
    app: ebookmgmt-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookmgmt-book
  template:
    metadata:
      labels:
        app: ebookmgmt-book
    spec:
      containers:
        - name: ebookmgmt-book
          image: username/ebookmgmt-book:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookmgmt-dashboard
  labels:
    app: ebookmgmt-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookmgmt-dashboard
  template:
    metadata:
      labels:
        app: ebookmgmt-dashboard
    spec:
      containers:
        - name: ebookmgmt-dashboard
          image: username/ebookmgmt-dashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ebookmgmt-rent
  labels:
    app: ebookmgmt-rent
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ebookmgmt-rent


---


apiVersion: v1
kind: Service
metadata:
  name: ebookmgmt-payment
  labels:
    app: ebookmgmt-payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ebookmgmt-payment


---


apiVersion: v1
kind: Service
metadata:
  name: ebookmgmt-book
  labels:
    app: ebookmgmt-book
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ebookmgmt-book


---


apiVersion: v1
kind: Service
metadata:
  name: ebookmgmt-dashboard
  labels:
    app: ebookmgmt-dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ebookmgmt-dashboard

