---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user18-ebookmgmt-payment
  labels:
    app: user18-ebookmgmt-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user18-ebookmgmt-payment
  template:
    metadata:
      labels:
        app: user18-ebookmgmt-payment
    spec:
      containers:
        - name: user18-ebookmgmt-payment
          image: 879772956301.dkr.ecr.ap-southeast-2.amazonaws.com/user18-ebookmgmt-payment:v0.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---


apiVersion: v1
kind: Service
metadata:
  name: user18-ebookmgmt-payment
  labels:
    app: user18-ebookmgmt-payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user18-ebookmgmt-payment

