---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user18-ebookmgmt-rent
  labels:
    app: user18-ebookmgmt-rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user18-ebookmgmt-rent
  template:
    metadata:
      labels:
        app: user18-ebookmgmt-rent
    spec:
      containers:
        - name: user18-ebookmgmt-rent
          image: 879772956301.dkr.ecr.ap-southeast-2.amazonaws.com/user18-ebookmgmt-rent:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: api.url.payment
              valueFrom:
                configMapKeyRef:
                  name: user18-ebookmgmt-rent-configmap
                  key: api.url.payment
#          args:
#            - /bin/sh
#            - -c
#            - touch /tmp/healty; sleep 90; rm -rf /tmp/healthy; sleep 600
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
#            exec:
#              command:
#              - cat
#              - /tmp/healthy
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---


apiVersion: v1
kind: Service
metadata:
  name: user18-ebookmgmt-rent
  labels:
    app: user18-ebookmgmt-rent
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user18-ebookmgmt-rent


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: user18-ebookmgmt-rent-configmap
data:
  api.url.payment: http://user18-ebookmgmt-payment:8080